title: Welcome!
author: Desmond Lim
email: desmondlimjw2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A website for introducing my background, experience, skills and portfolio.
theme: minima

# social links
github_username:  desmondlimjw # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
